name: obraprivada
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.0
  # Para peticiones HTTP
  http: ^1.6.0
  # Para manejo de variables de entorno (.env)
  flutter_dotenv: ^5.1.0
  # Opcional: Para iconos bonitos (usados en el c√≥digo)
  font_awesome_flutter: ^10.4.0
  intl: ^0.19.0 

  #  Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.10

  #  Notifications
  flutter_local_notifications: ^14.0.0
  
  # Google Sign-In
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/geobot.gif
    - .env
